# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/api/products/types
Accept: application/json

###

POST http://localhost:8080/api/products/types
Content-Type: application/json

{
  "name": "소품",
  "imagePath": "http://localhost:8080/public/image/test.jpg"
}

###

GET http://localhost:8080/api/products/types/1/sub-types
Accept: application/json

###

POST http://localhost:8080/api/products/sub-types
Content-Type: application/json

{
  "name": "셔츠",
  "typeId": 1
}

###